// The Lucide icons the prototypes use, under the names the app imports them by. The build
// renders each to SVG (scripts/prototypes-build.ts); a page shows one with
// <i data-icon="FolderKanbanIcon"></i>.
export {
  ArrowRightIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronsUpDownIcon,
  CircleIcon,
  CopyIcon,
  CpuIcon,
  EllipsisIcon,
  FileTextIcon,
  FolderKanbanIcon,
  GitMergeIcon,
  InfoIcon,
  LinkIcon,
  ListChecksIcon,
  LogOutIcon,
  MenuIcon,
  PencilIcon,
  PlusIcon,
  SearchIcon,
  Trash2Icon,
  TriangleAlertIcon,
  UploadIcon,
  UserCogIcon,
  UserIcon,
  UsersIcon,
  XIcon,
} from 'lucide-react'
