// The Lucide icons the prototypes use, under the names the app imports them by. The build
// renders each to SVG (scripts/prototypes-build.ts); a page shows one with
// <i data-icon="FolderKanbanIcon"></i>.
export {
  ArrowLeftIcon,
  ArrowRightIcon,
  BriefcaseIcon,
  BuildingIcon,
  CalendarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronsUpDownIcon,
  CircleCheckBigIcon,
  CircleCheckIcon,
  CircleIcon,
  CircleMinusIcon,
  CircleXIcon,
  ClockIcon,
  CopyIcon,
  CpuIcon,
  EllipsisIcon,
  FileTextIcon,
  FolderKanbanIcon,
  GitMergeIcon,
  GraduationCapIcon,
  InfoIcon,
  LinkIcon,
  ListChecksIcon,
  LockIcon,
  LogOutIcon,
  MailIcon,
  MenuIcon,
  PencilIcon,
  PhoneIcon,
  PlusIcon,
  SearchIcon,
  SendIcon,
  Trash2Icon,
  TriangleAlertIcon,
  UploadIcon,
  UserCogIcon,
  UserIcon,
  UserMinusIcon,
  UserPlusIcon,
  UsersIcon,
  XIcon,
} from 'lucide-react'
