// The hand-written part of the diagram: table groups and notes. datamodel/generate-dbml.ts
// reads everything else (columns, types, keys, indexes, references) from src/db/schema.ts.
//
// The generator adds these on its own, so leave them out of the notes here: ON DELETE
// rules, partial index WHERE clauses, and which composite foreign key a column is part of.
// Notes are plain text without apostrophes (the ChartDB converter reads single-quoted
// strings only).

export const projectNote = `
Data model for snowprofile on SQLite.

Tables in the auth and tenancy groups belong to Better Auth and its organization
plugin; their shape follows the plugin. Everything else is owned by the app.`

interface Group {
  name: string
  color: string
  // Section heading and comment lines above the group's tables.
  title: string
  comment?: string[]
  tables: string[]
}

// Every table belongs to one group; the generator warns about any that does not.
export const groups: Group[] = [
  {
    name: 'auth',
    color: '#BAB0AC',
    title: 'Auth (Better Auth core)',
    tables: ['user', 'session', 'account', 'verification'],
  },
  {
    name: 'tenancy',
    color: '#4E79A7',
    title: 'Tenancy (Better Auth organization plugin, no teams)',
    tables: ['organization', 'member', 'invitation'],
  },
  {
    name: 'catalogue',
    color: '#F28E2B',
    title: 'Catalogue',
    comment: [
      'Audit columns on every app-owned table: created_* always, updated_* where rows change,',
      'sys_deleted on entities users delete. Composite foreign keys keep references inside one',
      'organization; the diagram draws only the single-column part.',
    ],
    tables: [
      'technology_category',
      'technology',
      'technology_distinct_pair',
      'tender_criterion',
      'project_role',
    ],
  },
  {
    name: 'projects',
    color: '#59A14F',
    title: 'Projects',
    tables: [
      'customer',
      'contact_person',
      'project',
      'project_contact',
      'project_technology',
      'project_criterion_answer',
    ],
  },
  {
    name: 'people',
    color: '#E15759',
    title: 'People',
    tables: [
      'employee_profile',
      'education',
      'participation',
      'participation_technology',
      'participation_role',
      'own_project',
      'own_project_technology',
      'own_project_role',
      'update_request',
    ],
  },
]

// Notes for the audit columns of every app-owned table (those with created_by). A table's
// own column note replaces them.
export const auditNotes: Record<string, string> = {
  created_at: 'Audit. Epoch ms, set by the database.',
  created_by: 'Audit. Acting user, set by the app per request.',
  updated_at: 'Audit. Set by the app on update; trigger fallback.',
  updated_by: 'Audit. Acting user of the last change, set by the app.',
  sys_deleted: 'Audit. Logical delete, CHECK 0 or 1.',
}

interface TableNotes {
  note?: string
  columns?: Record<string, string>
  // Keyed by the index name in src/db/schema.ts.
  indexes?: Record<string, string>
}

export const tables: Record<string, TableNotes> = {
  user: {
    note: 'Better Auth user. One row per human, shared across organizations. Never hard-deleted: erasure anonymizes the row, so audit references stay valid.',
    columns: {
      id: 'UUIDv7, generated by the app through the Better Auth generateId hook.',
      name: 'Display name from Google or the seed. The name on CVs is employee_profile.full_name.',
      email: 'Sign-in email, stored lowercased.',
      email_verified: 'Boolean.',
      image: 'Avatar URL.',
      created_at: 'Epoch ms, UTC.',
      updated_at: 'Epoch ms, UTC.',
      locale:
        'The UI language the user chose: et or en (CHECK). Null until chosen; the cookie or the browser decides until then.',
    },
  },
  session: {
    note: 'Better Auth session. Carries the active organization, where the app opens after sign-in. Server functions take the organization from their input, not from here.',
    columns: {
      token: 'Session token held in the cookie.',
      expires_at: 'Epoch ms, UTC.',
      active_organization_id:
        'Organization plugin. The tenant every query in this session is scoped to.',
    },
  },
  account: {
    note: 'Better Auth credential or linked provider: Google, or a password for seeded demo users.',
    columns: {
      account_id: 'Identifier at the provider; equals user_id for the credential provider.',
      provider_id: 'google or credential.',
      password: 'Password hash, credential provider only. Exists only in seeded data.',
    },
  },
  verification: {
    note: 'Better Auth one-time values, such as OAuth state.',
  },
  organization: {
    note: 'Tenant. Every app-owned table carries organization_id, and every query filters by it. Deletion through Better Auth is disabled.',
    columns: {
      slug: 'URL-safe handle.',
      metadata: 'Plugin-defined JSON. Not used by the app.',
    },
  },
  member: {
    note: 'Membership: a user in an organization, with a role. A user can belong to several organizations.',
    columns: {
      role: 'admin or employee, configured as custom plugin roles. No CHECK: the plugin can store several roles comma-separated, and later roles need no migration.',
    },
  },
  invitation: {
    note: 'Invitation to an organization, shared as a link (no email in the MVP).',
    columns: {
      email: 'Invitee address, lowercased. Google sign-in with this address accepts it.',
      role: 'Role granted on acceptance: admin or employee.',
      status: 'pending, accepted, rejected, canceled.',
    },
  },
  technology_category: {
    note: 'A group in the technology catalogue, per organization. Seeded with Frontend, Backend, Data, Infra, Testing, and Other.',
    columns: {
      id: 'UUIDv7, generated by the app.',
      name_et: 'Bilingual: at least one of name_et and name_en (CHECK).',
      position: 'Sort order in lists and CVs.',
      sys_deleted:
        'Audit. Logical delete, CHECK 0 or 1. Refused while live technologies use the category.',
    },
    indexes: {
      technology_category_id_organization_id_unique: 'Target of composite foreign keys.',
    },
  },
  technology: {
    note: 'A catalogue entry, such as PostgreSQL. Anyone adds entries; admins rename, recategorize, and merge duplicates.',
    columns: {
      id: 'UUIDv7, generated by the app.',
      name: 'Proper name, the same in both languages.',
      normalized_name:
        'name lowercased with spaces and punctuation removed, set by the app. Catches Postgres SQL against PostgreSQL, and matches import values.',
      merged_into_id:
        'Set when an admin merges this entry into another: links move to the survivor and this row is soft-deleted. The import maps the old name to the survivor.',
      note: 'Plain text an admin writes, up to 1,000 characters, in one language: what the entry covers, why it is not a duplicate of a look-alike, or documentation links. Every member reads it.',
    },
    indexes: {
      technology_organization_id_normalized_name_unique: 'One live entry per name.',
      technology_id_organization_id_unique: 'Target of composite foreign keys.',
    },
  },
  tender_criterion: {
    note: 'A yes or no question that tenders ask about projects, such as automated tests or X-Road. Admins manage the list.',
    columns: {
      id: 'UUIDv7, generated by the app.',
      name_et: 'Bilingual: at least one of name_et and name_en (CHECK).',
      position: 'Sort order in the checklist.',
      sys_deleted: 'Audit. Logical delete, CHECK 0 or 1. Answers stay but no longer show.',
    },
    indexes: {
      tender_criterion_id_organization_id_unique: 'Target of composite foreign keys.',
    },
  },
  project_role: {
    note: 'A role in the role catalogue, such as arendaja / developer. Anyone adds entries with both names; admins rename and merge duplicates. Entries from the sheet migration can lack the English name.',
    columns: {
      id: 'UUIDv7, generated by the app.',
      name_et: 'Bilingual: at least one of name_et and name_en (CHECK).',
      normalized_name:
        'name_et, or name_en when it is missing, lowercased without diacritics, spaces, or punctuation, set by the app. Catches arendaja against Arendaja.',
      merged_into_id:
        'Set when an admin merges this entry into another: links move to the survivor and this row is soft-deleted.',
    },
    indexes: {
      project_role_organization_id_normalized_name_unique: 'One live entry per name.',
      project_role_id_organization_id_unique: 'Target of composite foreign keys.',
    },
  },
  customer: {
    note: 'An ordering organization (tellija), such as a ministry or Telia.',
    columns: {
      id: 'UUIDv7, generated by the app.',
      name: 'Proper name, the same in both languages.',
      sys_deleted:
        'Audit. Logical delete, CHECK 0 or 1. Refused while live projects name the customer.',
    },
    indexes: {
      customer_id_organization_id_unique: 'Target of composite foreign keys.',
    },
  },
  contact_person: {
    note: 'A person at a customer, given as a tender reference. Third-party personal data: only what references need.',
    columns: {
      id: 'UUIDv7, generated by the app.',
      no_longer_valid:
        'Boolean, CHECK 0 or 1. Set when the person can no longer act as a reference; CV tables leave them out.',
      note: 'Free text, such as no longer works at Telia. Not shown in CVs.',
    },
    indexes: {
      contact_person_id_organization_id_unique: 'Target of composite foreign keys.',
    },
  },
  project: {
    note: 'An organization project. Admins create and edit it; every member sees it in the project list. Own projects are in own_project instead.',
    columns: {
      id: 'UUIDv7, generated by the app.',
      customer_id: 'Null when the customer is unknown, for example after an import.',
      name: 'Proper name, the same in both languages.',
      normalized_name:
        'name lowercased with spaces and punctuation removed, set by the app, as on technology. Not unique: two projects can share a name. The import matches name variants from employee sheets against it, and the app warns about a similar existing name.',
      start_date:
        'Period start: YYYY-MM-DD, YYYY-MM, or YYYY, as precise as known (CHECK on the format). Shown as DD-MM-YYYY, MM-YYYY, or YYYY.',
      end_date:
        'Period end in the same formats; null while ongoing. CHECK end_date >= substr(start_date, 1, length(end_date)).',
      tender_reference:
        'Procurement reference number (viitenumber). Admins edit; participants read.',
      total_hours: 'Approximate number: see total_hours_qualifier. Admins edit; participants read.',
      total_hours_qualifier:
        'exact, approximately, more_than (CHECK). Null exactly when total_hours is null (CHECK).',
      cost: 'Whole euros. Approximate number: see cost_qualifier. Admins edit; participants read.',
      cost_qualifier:
        'exact, approximately, more_than (CHECK). Null exactly when cost is null (CHECK).',
      import_ref:
        'The project number in the imported sheet, such as 10. A re-run of the import updates the project with this ref instead of adding another. Null for projects created in the app.',
      updated_at:
        'Audit. Last change, shown on the project. Set by the app on update; trigger fallback.',
      sys_deleted:
        'Audit. Logical delete, CHECK 0 or 1. Deleted projects leave every list, search, and CV.',
    },
    indexes: {
      project_id_organization_id_unique: 'Target of composite foreign keys.',
    },
  },
  project_contact: {
    note: 'A contact person given as a reference for a project. The app checks that the person belongs to the project customer. Rows are inserted and deleted, never updated.',
    columns: {
      organization_id:
        'Tenant key, equal to the organization of both sides through the composite foreign keys.',
    },
  },
  technology_distinct_pair: {
    note: 'Two technologies an admin marked "Not a duplicate", so the near-duplicate rule never suggests them again. Inserted once, never updated.',
    columns: {
      technology_id: 'The lower of the two IDs, so a pair is stored once.',
      other_technology_id: 'The higher of the two IDs.',
      organization_id:
        'Tenant key, equal to the organization of both technologies through the composite foreign keys.',
    },
  },
  project_technology: {
    note: 'A technology used on a project. Rows are inserted and deleted, never updated.',
    columns: {
      organization_id:
        'Tenant key, equal to the organization of both sides through the composite foreign keys.',
    },
  },
  project_criterion_answer: {
    note: 'A project answer to a tender criterion. No row means not answered yet.',
    columns: {
      organization_id:
        'Tenant key, equal to the organization of both sides through the composite foreign keys.',
      answer: 'Boolean, CHECK 0 or 1: yes or no.',
      note: 'Optional detail beyond yes or no, such as REST and SOAP, or Liquibase for translations. One language: an internal checklist note, not CV text.',
    },
  },
  employee_profile: {
    note: 'A member CV data in one organization. One per user and organization, created with the membership. A leaver keeps the profile with left_date set; whether and when it is anonymized is an open question (docs/product.md, Leavers).',
    columns: {
      id: 'UUIDv7, generated by the app.',
      user_id:
        'Not a foreign key to member: Better Auth deletes member rows on removal, and a leaver profile outlives that.',
      full_name: 'Name as it appears on CVs. Starts as user.name.',
      join_date: 'Date the person joined the organization: YYYY-MM-DD (CHECK on the format).',
      left_date:
        'Date the person left the organization: YYYY-MM-DD; null while employed. CHECK left_date >= join_date. Search and CV selection leave out leavers by default; their participations stay on projects. Retention is open (docs/product.md, Leavers).',
      birth_date:
        'Optional: YYYY-MM-DD. Shown only to admins and the person; in a CV only when chosen explicitly. No column holds a personal ID code.',
      confirmed_at:
        'Epoch ms of the last time the person confirmed the profile is current. Null until the first confirmation.',
      updated_at:
        'Audit. Set by the app on update; trigger fallback. The profile last change is the latest updated_at across it, its education, participations, and own projects.',
    },
    indexes: {
      employee_profile_id_organization_id_unique: 'Target of composite foreign keys.',
    },
  },
  education: {
    note: 'An education entry on a profile; a profile has several.',
    columns: {
      id: 'UUIDv7, generated by the app.',
      institution_et: 'Bilingual: at least one of institution_et and institution_en (CHECK).',
      field_et: 'Field of study.',
      degree_et: 'Degree or level, such as MSc.',
      start_date: 'YYYY-MM-DD, YYYY-MM, or YYYY. Optional: older entries often lack it.',
      end_date:
        'YYYY-MM-DD, YYYY-MM, or YYYY; null while ongoing. CHECK end_date >= substr(start_date, 1, length(end_date)).',
    },
  },
  participation: {
    note: 'A person on an organization project. A person can have several on one project, for different periods or roles.',
    columns: {
      id: 'UUIDv7, generated by the app.',
      start_date: 'YYYY-MM-DD, YYYY-MM, or YYYY.',
      end_date:
        'YYYY-MM-DD, YYYY-MM, or YYYY; null while ongoing. CHECK end_date >= substr(start_date, 1, length(end_date)).',
      hours: 'Approximate number: see hours_qualifier.',
      hours_qualifier:
        'exact, approximately, more_than (CHECK). Null exactly when hours is null (CHECK).',
      tasks_et: 'What the person did.',
    },
    indexes: {
      participation_id_organization_id_unique: 'Target of composite foreign keys.',
    },
  },
  participation_technology: {
    note: 'A technology the person used in a participation: a subset of the project technologies, or an addition to them. Rows are inserted and deleted, never updated.',
    columns: {
      organization_id:
        'Tenant key, equal to the organization of both sides through the composite foreign keys.',
    },
  },
  participation_role: {
    note: 'A role the person had in a participation; a participation has one or more. Rows are inserted and deleted, never updated.',
    columns: {
      organization_id:
        'Tenant key, equal to the organization of both sides through the composite foreign keys.',
    },
  },
  own_project: {
    note: 'A project that appears only on its owner CV: from an earlier employer, or several engagements merged into one. A separate table, so no project list or search over project can include it. Holds the project and the owner participation in one row.',
    columns: {
      id: 'UUIDv7, generated by the app.',
      profile_id: 'The owner.',
      employer: 'The company the work was done for, when it was not this organization.',
      customer_name:
        'Free text: the customer is outside the organization customer list. No contact persons are stored for own projects.',
      start_date: 'YYYY-MM-DD, YYYY-MM, or YYYY.',
      end_date:
        'YYYY-MM-DD, YYYY-MM, or YYYY; null while ongoing. CHECK end_date >= substr(start_date, 1, length(end_date)).',
      total_hours: 'Project total. Approximate number: see total_hours_qualifier.',
      total_hours_qualifier:
        'exact, approximately, more_than (CHECK). Null exactly when total_hours is null (CHECK).',
      cost: 'Whole euros. Approximate number: see cost_qualifier.',
      cost_qualifier:
        'exact, approximately, more_than (CHECK). Null exactly when cost is null (CHECK).',
      hours: 'Owner hours. Approximate number: see hours_qualifier.',
      hours_qualifier:
        'exact, approximately, more_than (CHECK). Null exactly when hours is null (CHECK).',
    },
    indexes: {
      own_project_id_organization_id_unique: 'Target of composite foreign keys.',
    },
  },
  own_project_technology: {
    note: 'A catalogue technology used on an own project. Rows are inserted and deleted, never updated.',
    columns: {
      organization_id:
        'Tenant key, equal to the organization of both sides through the composite foreign keys.',
    },
  },
  own_project_role: {
    note: 'The owner role on an own project; an own project has one or more. Rows are inserted and deleted, never updated.',
    columns: {
      organization_id:
        'Tenant key, equal to the organization of both sides through the composite foreign keys.',
    },
  },
  update_request: {
    note: 'An admin asks a person to bring their profile up to date. The person sees open requests on sign-in; confirming the profile closes them.',
    columns: {
      id: 'UUIDv7, generated by the app.',
      message: 'Optional note from the admin, such as add the 2026 projects.',
      closed_at:
        'Epoch ms. Set when the person confirms the profile or an admin cancels the request; null while open.',
      closed_reason: 'confirmed or canceled (CHECK). Null exactly when closed_at is null (CHECK).',
      created_at: 'Audit. When the request was made. Epoch ms, set by the database.',
      created_by: 'Audit. The requesting admin, set by the app per request.',
      updated_by: 'Audit. Acting user of the last change: who closed it.',
    },
    indexes: {
      update_request_profile_id_open_unique: 'At most one open request per profile.',
    },
  },
}
